[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Baio"
authors = [{name = "Noah Bruderer", email = "noah.bruderer@gmail.com"}]
dynamic = ["version", "description"]
